//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsf.Olss.Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\"(DESCRIPTION=(ADDRESS=(PORT=1521)(HOST=sndsfpdaca-scan.corp.dipostar" +
            ".com)(PROTOCOL=TCP))(CONNECT_DATA=(SERVICE_NAME=ACAPROD)))\";Persist Security Inf" +
            "o=True;User ID=PDBACA02;Password=Pdbaca2014;Unicode=True")]
        public string ACAPRODVM {
            get {
                return ((string)(this["ACAPRODVM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("DATA SOURCE=192.168.132.107:1521/MFQA;PASSWORD=OLSS_MFAPPL;PERSIST SECURITY INFO=" +
            "True;USER ID=OLSS_MFAPPL")]
        public string OLSSMFAPPLConnectionString {
            get {
                return ((string)(this["OLSSMFAPPLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.1.1.38\\SQLEXP2012;Initial Catalog=olss_prod_4_20210310_crMgtRpt_P1_uat" +
            ";Persist Security info=True;user id=sa;password=Ultron999;MultipleActiveResultSe" +
            "ts=True")]
        public string olss_prod_4ConnectionString {
            get {
                return ((string)(this["olss_prod_4ConnectionString"]));
            }
        }
    }
}
